### ISSUE TITLE
검색 페이지 화면 구현

### ISSUE THREAD

**Issue by haizellatte** [trade-market/trade-market-FE#15]
## Todo
- [x] 전체적인 레이아웃 구현
- [x] 검색 
- [x] 최근 검색어
- [x] 이웃들이 많이 찾는 거래

## Detail
- [x] 최근 검색어가 없을경우 '최근 검색어가 없습니다'
- [x] 최근 검색어는 최대 5개만 표시된다.
- [x] 최근검색어 개별 삭제
- [x] 최근 검색어 전체 삭제

**Comment by haizellatte** [comment]
## 구현 내용
### 최근 검색어
- LocalStorage Set, Get 구현
- 최근 검색어 추가 / 단일 삭제 / 전체 삭제 기능
- 최근 검색어 최대 5개까지만 노출
- Click 및 EnterKey로 검색어 추가 가능
### 이웃들이 많이 찾는 거래
- 배열 요소 중 개수가 가장 많은 순서대로 랭킹

<br />

## 구현 화면
![Animation](https://github.com/trade-market/trade-market-FE/assets/115685195/676cf995-ecc2-48d2-b860-b227ad97e41d)
