### ISSUE TITLE
공용 컴포넌트 화면 구현

### ISSUE THREAD

**Issue by haizellatte** [trade-market/trade-market-FE#2]
## Todos
- [x] 메인 헤더
- [x] 공용 헤더 레이아웃
- [x] 네이게이션 바
- [x] 공용 헤더 뒤로가기 버튼

## Detail
- [x] 네비게이션 바 active
- [x] 헤더 및 네비게이션바 로그인 화면에서 none 처리
- [x] 뒤로 가기 버튼이 없는 회면에서는 none 처리

**Comment by haizellatte** [comment]
구현 완료.
