### ISSUE TITLE
[오퍼 : 직접 작성하기] 댓글 달기 상세 페이지 화면 구현

### ISSUE THREAD

**Issue by haizellatte** [trade-market/trade-market-FE#29]
## Description
오퍼 - 직접 작성하기 로직의 페이지 화면 구현
## Progress
- [x] 2/6 사진 업로드 페이지
- [x] 3/6 희망 물품 및 카테고리 선정 페이지
- [x] 4/6 예상 가격대 책정 페이지
- [x] 5/6 전달 사항 작성 페이지
- [x] 6/6 최종 확인 페이지
## Todo
- [x] 공용 컴포넌트 (progressBar)
- [x] bottomSheet
- [x] 사진 업로드 기능
- [x] 가격대 책정 input Range
- [x] Route 작업
- [x] Redux 작업
