### ISSUE TITLE
오퍼 상세 페이지 하단 화면 구현

### ISSUE THREAD

**Issue by Yongveloper** [trade-market/trade-market-FE#34]
## Description
![image](https://github.com/trade-market/trade-market-FE/assets/64254228/e7648dc8-79b5-4a34-8f59-885effb7e9ab)

## Todo
- [x] 댓글 컴포넌트 구현
- [x] 상단 헤더의 수정 및 삭제 메뉴 추가
- [x] 좋아요, 댓글 컴포넌트 구현
