### ISSUE TITLE
[거래 생성 페이지] 화면 구현 (물물/재능, 1:1/offer)

### ISSUE THREAD

**Issue by haizellatte** [trade-market/trade-market-FE#41]
## Description
게시물 작성 - 재능교환 - 1:1 거래 생성 

## Todo
- [x] 거래 방법 선택 화면 개별 route
- [x] 재사용 컴포넌트 분리(PostSection, Drop Down, textArea 등)
- [x] writeButton 모달
- [x] 업로드한 사진 개별 삭제
- [x] 거래 마감일 캘린더
- [x] 거래 마감일 선택 시 현재 날짜 이전은 선택 못하게 block
- [x] 가격 제안 rangebar
- [x] 거래 방법 선택 페이지 구현
- [x] 게시물 작성 페이지 구현
- [x] 최종 확인 페이지 구현
- [x] 1:1 페이지 -> 재능 교환/물물교환 모두 같은 페이지를 공유하겠금 코드 확장

## 제한 사항 (max)
- 제목 : 50자
- 내용 : 500자
- 사진 최대 5개
