### ISSUE TITLE
[채팅페이지] 채팅 기능 수정

### ISSUE THREAD

**Issue by haizellatte** [trade-market/trade-market-FE#58]
## Todo
- [x] send 버튼 동작 활성화
- [x] input value 없을 시 enterkey Event 비활성화
- [x] 마지막 채팅으로 scrollY 이동
